(function(){
  const STYLE=`
  .enhancedStats{display:grid!important;grid-template-columns:1fr 1fr;gap:0!important;overflow:hidden}
  .enhancedStats .statCell{padding:14px 12px;border-bottom:1px solid #252f3e}
  .enhancedStats .statCell:nth-child(odd){border-right:1px solid #252f3e}
  .enhancedStats .statCell:nth-last-child(-n+2){border-bottom:0}
  .enhancedStats .statCell strong{display:block;font-size:20px;margin-top:4px}
  .enhancedStats .statCell .sub{display:block;font-size:12px;color:#8995a6;margin-top:2px}
  .historyBottom{margin-top:26px}
  .historyBottom .ghost{margin-top:0}
  `;
  if(!document.getElementById('liftlog-enhancements-style')){let s=document.createElement('style');s.id='liftlog-enhancements-style';s.textContent=STYLE;document.head.appendChild(s)}
  function chartSetup2(cv){let r=cv.getBoundingClientRect(),d=devicePixelRatio||1,w=Math.max(280,r.width),h=cv.height;cv.width=Math.round(w*d);cv.height=Math.round(h*d);let ctx=cv.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);return{ctx,w,h}}
  function detailedLine(cv,vals,labels,step,unit){let s=chartSetup2(cv);if(!s)return;let{ctx,w,h}=s,left=52,right=10,top=12,bottom=28,plotW=w-left-right,plotH=h-top-bottom,max=Math.max(step,Math.ceil(Math.max(...vals,0)/step)*step),count=Math.max(1,Math.round(max/step));ctx.font='10px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif';ctx.lineWidth=1;for(let i=0;i<=count;i++){let v=i*step,y=top+plotH-(v/max)*plotH;ctx.strokeStyle='rgba(140,153,170,.14)';ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(w-right,y);ctx.stroke();ctx.fillStyle='#8995a6';ctx.textAlign='right';ctx.fillText(v.toLocaleString()+(unit?' '+unit:''),left-7,y+3)}vals.forEach((v,i)=>{let x=left+(plotW*i)/Math.max(1,vals.length-1);ctx.strokeStyle='rgba(140,153,170,.08)';ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,top+plotH);ctx.stroke();ctx.fillStyle='#8995a6';ctx.textAlign='center';ctx.fillText(labels[i]||'',x,h-9)});ctx.beginPath();vals.forEach((v,i)=>{let x=left+(plotW*i)/Math.max(1,vals.length-1),y=top+plotH-(v/max)*plotH;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#aebcff';ctx.lineWidth=2.5;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();vals.forEach((v,i)=>{let x=left+(plotW*i)/Math.max(1,vals.length-1),y=top+plotH-(v/max)*plotH;ctx.fillStyle='#aebcff';ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()})}
  function monthVolume(name){let now=new Date(),start=new Date(now);start.setDate(start.getDate()-29);start.setHours(0,0,0,0);return setsFor(name).filter(s=>new Date(s.date)>=start).reduce((a,s)=>a+s.weight*s.reps,0)}
  function weekVolume(name){let now=new Date(),start=new Date(now);start.setDate(start.getDate()-6);start.setHours(0,0,0,0);return setsFor(name).filter(s=>new Date(s.date)>=start).reduce((a,s)=>a+s.weight*s.reps,0)}
  function renderStats(name){let a=setsFor(name),sets=a.map(s=>({...s,volume:s.weight*s.reps})),pr=sets.sort((x,y)=>y.volume-x.volume||y.weight-x.weight)[0]||{weight:0,reps:0,volume:0},rm=oneRM(name),six=rm/1.2,eight=rm/(1+8/30),box=$('bestWeight')?.closest('.statGrid');if(!box)return;box.classList.add('enhancedStats');box.innerHTML=`<div class="statCell"><span class="muted">PR volume · 1 set</span><strong>${Math.round(pr.volume).toLocaleString()} lb</strong><span class="sub">Total weight</span></div><div class="statCell"><span class="muted">Best set</span><strong>${pr.weight||0} lb × ${pr.reps||0}</strong><span class="sub">Weight + reps</span></div><div class="statCell"><span class="muted">Weekly volume</span><strong>${Math.round(weekVolume(name)).toLocaleString()} lb</strong><span class="sub">Last 7 days</span></div><div class="statCell"><span class="muted">Monthly volume</span><strong>${Math.round(monthVolume(name)).toLocaleString()} lb</strong><span class="sub">Last 30 days</span></div><div class="statCell"><span class="muted">1RM</span><strong>${Math.round(rm)} lb</strong><span class="sub">Epley estimate</span></div><div class="statCell"><span class="muted">Estimated 6–8 RM</span><strong>${Math.round(eight)}–${Math.round(six)} lb</strong><span class="sub">Epley-derived range</span></div>`}
  function moveHistoryBottom(){let p=$('performance');if(!p)return;let toggle=$('historyToggle'),list=$('historyList');if(!toggle||!list)return;let old=p.querySelector('.historyBottom');if(old)old.remove();let wrap=document.createElement('div');wrap.className='historyBottom';wrap.innerHTML='<div class="sectionTitle"><h3>History</h3></div>';wrap.appendChild(toggle);wrap.appendChild(list);p.appendChild(wrap);toggle.classList.remove('full');toggle.textContent=list.classList.contains('hidden')?'Show history':'Hide history';toggle.onclick=()=>{list.classList.toggle('hidden');toggle.textContent=list.classList.contains('hidden')?'Show history':'Hide history'}}
  function renderHistoryBottom(){let list=$('historyList');if(!list)return;let all=(data.workouts||[]).map(x=>({...x,type:'Workout'})).sort((a,b)=>new Date(b.date)-new Date(a.date));list.innerHTML=all.map(x=>`<div class="card historyItem"><div><strong>${esc(x.routine)}</strong><span class="muted small">${fd(x.date)} • ${x.durationMin||0} min • ${Math.round(x.volume||0).toLocaleString()} lb volume</span></div><span class="pill">${(x.exercises||[]).reduce((a,e)=>a+(e.sets||[]).length,0)} sets</span></div>`).join('')||'<div class="empty">No workout history yet.</div>'}
  function performanceEnhanced(){let names=Object.keys(EX).sort();$('progressExercise').innerHTML=names.map(n=>`<option>${esc(n)}</option>`).join('');let n=$('progressExercise').value;renderStats(n);let a=setsFor(n),trend={};a.forEach(s=>trend[dk(s.date)]=Math.max(trend[dk(s.date)]||0,s.weight*(1+s.reps/30)));detailedLine($('strengthChart'),Object.values(trend).slice(-14),Object.keys(trend).slice(-14).map(d=>d.slice(5)),5,'lb');let mus={};data.workouts.forEach(w=>(w.exercises||[]).forEach(e=>{let m=info(e.name)[0];mus[m]=(mus[m]||0)+e.sets.reduce((q,s)=>q+(+s.weight||0)*(+s.reps||0),0)}));bars($('muscleChart'),mus);let vals=[],labels=[];for(let i=7;i>=0;i--){let end=new Date();end.setHours(0,0,0,0);end.setDate(end.getDate()-i*7);let start=new Date(end);start.setDate(start.getDate()-7);vals.push(data.workouts.filter(w=>new Date(w.date)>=start&&new Date(w.date)<end).length);labels.push(i===0?'This wk':i+'w ago')}detailedLine($('frequencyChart'),vals,labels,1,'workouts');let avg=(vals.reduce((x,y)=>x+y,0)/vals.length).toFixed(1),curWeek=vals[vals.length-1];$('progressDetails').innerHTML=`<div class="card"><b>Training frequency</b><p class="muted small">8-week average: ${avg} workouts/week • Current week: ${curWeek} • ${curWeek>=avg?'At or above':'Below'} your recent average.</p></div><div class="card"><b>Progression recommendation</b><p class="muted small">${esc(suggest(n))}. Rep PRs and weight PRs are tracked independently. Estimated 1RM uses the Epley formula.</p></div>`;renderHistoryBottom();moveHistoryBottom()}
  function dashboardEnhanced(){let t=week(),days=new Set(t.w.map(x=>dk(x.date)));$('weekWorkouts').textContent=`${t.w.length} workout${t.w.length===1?'':'s'}`;$('weekFrequency').textContent=`${days.size} training day${days.size===1?'':'s'}`;$('volumeWeek').textContent=`${Math.round(t.vol).toLocaleString()} lb`;let ws=new Date(),day=(ws.getDay()+6)%7;ws.setHours(0,0,0,0);ws.setDate(ws.getDate()-day);let vals=[],labels=[];for(let i=0;i<7;i++){let d=new Date(ws);d.setDate(ws.getDate()+i);vals.push(data.workouts.filter(w=>dk(w.date)===dk(d)).reduce((a,x)=>a+(+x.volume||0),0));labels.push(d.toLocaleDateString(undefined,{weekday:'short'}))}detailedLine($('volumeChart'),vals,labels,5000,'lb');let prs=Object.keys(EX).map(n=>[n,best(n).weight]).filter(x=>x[1]).sort((a,b)=>b[1]-a[1]).slice(0,5);$('prs').innerHTML=prs.map(x=>`<div class="card pr"><span><b>${esc(x[0])}</b><br><span class="muted small">Weight PR</span></span><b>${x[1]} lb</b></div>`).join('')||'<div class="empty">Complete a workout to start tracking PRs.</div>'}
  window.performance=performanceEnhanced;window.updateProgress=function(n){renderStats(n)};window.dashboard=dashboardEnhanced;document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{dashboardEnhanced();performanceEnhanced()},0));
})();
